language: go

go:
  - 1.10.x

install: go get -v ./...

before_script: chmod +x $TRAVIS_BUILD_DIR/build.sh

script: $TRAVIS_BUILD_DIR/build.sh

deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_TOKEN
  file:
    - $TRAVIS_BUILD_DIR/tar/cloudflare-ddns-darwin-386.tar.gz
    - $TRAVIS_BUILD_DIR/tar/cloudflare-ddns-darwin-amd64.tar.gz
    - $TRAVIS_BUILD_DIR/tar/cloudflare-ddns-linux-386.tar.gz
    - $TRAVIS_BUILD_DIR/tar/cloudflare-ddns-linux-amd64.tar.gz
    - $TRAVIS_BUILD_DIR/tar/cloudflare-ddns-linux-arm64.tar.gz
    - $TRAVIS_BUILD_DIR/tar/cloudflare-ddns-linux-arm.tar.gz
    - $TRAVIS_BUILD_DIR/tar/cloudflare-ddns-windows-386.tar.gz
    - $TRAVIS_BUILD_DIR/tar/cloudflare-ddns-windows-amd64.tar.gz
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
